### ISSUE TITLE
Check for/ DWYL_API_KEY before AUTH_API_KEY

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug#14]
At present we are using `SECRET_KEY_BASE` as our single environment variable:
https://github.com/dwyl/auth_plug/blob/1ebb60938487da7e740a79b2a4639b29f2ba44ac/.env_sample#L1
Which is then used in:
https://github.com/dwyl/auth_plug/blob/1ebb60938487da7e740a79b2a4639b29f2ba44ac/lib/token.ex#L7

As part of our Quest to only have a **_Single_ Environment Variable** to run the App on `localhost` https://github.com/dwyl/auth/issues/42 we need to _use_ that variable in our `Token` module.

# Todo

+ [x] Check for `DWYL_API_KEY` as the `@secret` in `Token` module
+ [x] Test for it! 💯 
+ [x] Split the `DWYL_API_KEY` on `/` and 
  + [x] use the _second_ half (corresponding to the `client_secret`) to verify the `JWT`
  + [x] If `JWT` verification fails, send the _first_ half of the `DWYL_API_KEY` (corresponding to the `client_id`) as the `client_id` in the URL query param so that the `Auth` App can verify it.

**Comment by nelsonic** [comment]
https://github.com/dwyl/auth_plug/blob/b612845c62d7257c4a665f83faea3c31debacbbf/lib/token.ex#L17-L21

https://github.com/dwyl/auth_plug/blob/b612845c62d7257c4a665f83faea3c31debacbbf/lib/auth_plug.ex#L160-L167

**Comment by nelsonic** [comment]
I've got this working. Closing. ✅
