### ISSUE TITLE
Make decoded JWT available on conn.assigns.person

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug#17]
At present we are assigning the verified and decode JWT to `conn.assigns.decoded`:
https://github.com/dwyl/auth_plug/blob/3bcdac1517b97fc565b20508addf27ddd26866bc/lib/auth_plug.ex#L100

This made sense at the time we wrote it because the `:decoded` key is the decoded JWT. 💭 
But in the context of an App _using_ `auth_plug` I find myself writing `conn.assigns.decoded.id` a lot when I think it would be more _intuitive_ to write `conn.assigns.person.id` ... 

Given that nobody `else` is using `auth_plug` yet, _now_ is the time to make this change.
I think it will make things a lot clearer for people in the future. 

# Todo

+ [x] Rework `create_session/3` to assign the decoded `claims` to `conn.assigns.person`
https://github.com/dwyl/auth_plug/blob/3bcdac1517b97fc565b20508addf27ddd26866bc/lib/auth_plug.ex#L97-L103
+ [x] Assign the original JWT to `conn.assigns.jwt` i.e. `assign(:jwt, jwt)` instead of `assign(:person, jwt)`
+ [x] Define the session as `jwt` instead of person i.e. `put_session(:jwt, jwt)`
+ [x] Update the `cond` block to look for the `jwt` by the `:jwt` key instead of `:person`:
https://github.com/dwyl/auth_plug/blob/3bcdac1517b97fc565b20508addf27ddd26866bc/lib/auth_plug.ex#L33-L59
+ [x] Update the tests.
+ [x] Publish a new version with the _breaking_ change. (_We don't need a major bump as nobody is using the package yet so `1.1.0` is fine_)

**Comment by nelsonic** [comment]
Going to get this done _now_ as it's the penultimate thing on my list before assigning [auth/pull/43](https://github.com/dwyl/auth/pull/43#issuecomment-621931118)
I expect it to take around `T25m` but I've estimated `T1h` for tidying up tests and docs. ⏳

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/auth_plug/1.1.0 ✅
