### ISSUE TITLE
Create Auth Plug and Publish Package to Hex.pm

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug#2]
One of the beauties of the [`Plug`](https://hexdocs.pm/plug) specification for composable web app modules
is that plugs can be used as ["Middleware"](https://en.wikipedia.org/wiki/Middleware) similar to a Plugin or Hook.

# Todo

+ [x] Create a Plug that checks for a valid JWT in: 
  + [x] headers
  + [x] cookies 
  + [x] URL
  + [x] Sessions: https://www.phoenixframework.org/blog/sessions
+ [x] Publish Package to Hex.pm https://hex.pm/packages/auth_plug
![image](https://user-images.githubusercontent.com/194400/78419923-715c1280-7642-11ea-9b09-fcd65e2c79aa.png)

Thankfully @SimonLab has already done _some_ of the work for this:
https://github.com/dwyl/auth-mvp/blob/master/lib/plugs/authenticate_person.ex

We just need to add:
+ [x] Redirect to `auth.dwyl.com` #5 > https://dwylauth.herokuapp.com (for now)
+ [x] Include [HTTP `referer`](https://en.wikipedia.org/wiki/HTTP_referer) prop in URL
+ [x] Minimise configuration
+ [ ] Documentation!
  + [x] inline function docs
  + [x] diagram: https://github.com/dwyl/auth_plug/issues/2#issuecomment-620557929
  + [x] Readme background & usage instructions
  + [ ] Demo app: https://github.com/dwyl/auth_plug_example/issues/1

**Comment by nelsonic** [comment]
Seeing the following error when attempting to set the Phoenix Session in the `auth_plug`:

```
** (ArgumentError) cannot fetch session without a configured session plug
```

For context my goal is to create a plug that does _everything_ related to `auth` in a Phoenix App.
I might need to make another diagram to explain it. 💭

**Comment by nelsonic** [comment]
Some useful insight in this question/answer:
https://stackoverflow.com/questions/31983077/how-can-i-set-session-in-setup-when-i-test-phoenix-action-which-need-user-id-in/31983168#31983168

**Comment by nelsonic** [comment]
```
** (ArgumentError) session not fetched, call fetch_session/2
```

**Comment by nelsonic** [comment]
added `plug :fetch_session` to the test server and now see:
```
** (ArgumentError) cannot fetch session without a configured session plug
```

**Comment by nelsonic** [comment]
Reading: https://stackoverflow.com/questions/36694622/sessions-in-phoenix-app sadly not conclusive.

**Comment by nelsonic** [comment]
```
** (ArgumentError) cookie store expects :signing_salt as option
```

**Comment by nelsonic** [comment]
Reading: https://stackoverflow.com/questions/42661971/cookie-store-expects-conn-secret-key-base-to-be-at-least-64-bytes-but-its-al

**Comment by nelsonic** [comment]
```
** (ArgumentError) cookie store expects conn.secret_key_base to be set
```
Argument error driven development ... 🙄

**Comment by nelsonic** [comment]
Diagram:
![auth_plug-diagram](https://user-images.githubusercontent.com/194400/80484054-0060ff80-894f-11ea-80fc-537c1a9779a6.png)

**Comment by nelsonic** [comment]
# GIF of `AUTH_API_KEY` Setup for `auth_plug` Example:
![auth_plug_example_setup](https://user-images.githubusercontent.com/194400/80759455-3eb51500-8b2f-11ea-98fe-6e5154bfb349.gif)

**Comment by nelsonic** [comment]
Try it: https://auth-plug-example.herokuapp.com/admin 🚀 
![image](https://user-images.githubusercontent.com/194400/80765920-154eb600-8b3c-11ea-90d4-a64224d31a5b.png)
