### ISSUE TITLE
Update Instructions for Getting AUTH_API_KEY

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug#25]
In light of the changes made in https://github.com/dwyl/auth/pull/85, specifically the creation of Apps, 
we need to update the instructions for creating an `AUTH_API_KEY`.

# Todo

+ [x] Create a GIF of the new steps.
  > **Note**: it's still the same _number_ of steps and fields to complete and hopefully clearer.
+ [x] Summarise the steps verbally for anyone who could be confused by the GIF
+ [x] Link to the home page of the auth app: https://dwylauth.herokuapp.com (_instead of deep-linking to `/apps/new`_) as the new workflow is quite clear and it's basically impossible to get it wrong. 
+ [x] Create PR with update
+ [x] Assign PR for review

For reference, these are the current instructions with an illustrative (animated) GIF:
<hr />

### 6. Get and Set the `AUTH_API_KEY` Environment Variable

Visit: https://dwylauth.herokuapp.com/settings/apikeys/new
and create a New API Key.

![auth_plug_example_setup](https://user-images.githubusercontent.com/194400/80759455-3eb51500-8b2f-11ea-98fe-6e5154bfb349.gif)

Save the key as an environment variable named `AUTH_API_KEY`.
Remember to `export` the environment variable
or add it to an `.env` file which should be in your `.gitignore` file.

**Comment by nelsonic** [comment]
New GIF:
![dwyl-auth-app-api-key-setup](https://user-images.githubusercontent.com/194400/93143513-0712c800-f6e0-11ea-9020-c253805d66df.gif)

**Comment by nelsonic** [comment]
New GIF included in PR #26
