### ISSUE TITLE
Optional Auth

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug#27]
There are often cases in our App(s) where we want to display personalised content 
**`if`** the person is logged in ***or*** display generic info if they are not logged in. 

At present we only have the ability to **`always`** require authentication for a given route.
What we want is _optional_ auth which initialises the session if the cookie is set but ignores it if not.

# Todo

+ [x] Create helper function that merely checks the session/cookie for JWT 
  + [x] and ensures that the session data is assigned on the conn so that any routes/templates that can benefit from having `conn.assigns.person` defined will have it.
+ [ ] Document how to use this "optional" auth in a `router.ex` for a Phoenix App.

Relevant to: https://github.com/dwyl/auth/issues/69

**Comment by nelsonic** [comment]
Done and documented: https://github.com/dwyl/auth_plug#optional-auth ✅
