### ISSUE TITLE
Update Logout HTTP Request METHOD from GET to POST

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug#39]
As discussed in the PR that added **logout**, we should replace the GET request with a POST.

# Todo

+ [x]  Update method here in **auth_plug**
+ [x] Update **auth** route to POST
+ [x] Update tests **auth** to use POST request
+ [ ] Publish a new version to Hex.pm

**Comment by SimonLab** [comment]
I want to test the post request directly in the auth app by changing the dependency there.
To make sure the change on the dependency are taken into account we can add the `path` and `override` option:
```elixir
 {:auth_plug, "~> 1.4.6", path: "deps/auth_plug", override: true},
```
Once everything works I'll do the change on the library itself to make it publishable

**Comment by SimonLab** [comment]
Using the post request with an empty body:

```elixir
{:ok, response} = 
  "#{auth_url}/end_session/#{client_id}/#{claims.sid}/"
   |> @httpoison.post('') # empty string as body
  |> parse_body_response()           
```

The `parse_body_response` is failing because we don't have defined the post endpoint on auth yet:
![image](https://user-images.githubusercontent.com/6057298/144209838-94cf4075-fafa-4954-9a3b-a26bf027857e.png)

**Comment by SimonLab** [comment]
PR #41 ready for review

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/auth_plug/1.4.7
