### ISSUE TITLE
Update Dependencies via Dependabot 🤖 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/auth_plug#51]
2 dependencies currently out-of-date: [![Libraries.io dependency status](https://img.shields.io/librariesio/release/hex/auth_plug?logoColor=brightgreen&style=flat-square)](https://github.com/dwyl/auth_plug/blob/master/mix.exs)

![image](https://user-images.githubusercontent.com/194400/159305944-090701dd-d828-4a43-a826-89aca3def68b.png)

https://libraries.io/hex/auth_plug
![image](https://user-images.githubusercontent.com/194400/159300117-5695929b-ee48-4e61-9f7c-38058d789b3c.png)

# Todo

+ [x] update all dependencies
+ [x] bump package version in `mix.ex`
+ [x] create PR to update
+ [x] confirm everything is working
+ [x] publish new version to Hex.pm

This should be quick. But on the off-chance that it isn't please post a comment with any issues faced.
